$ErrorActionPreference = 'Stop'

# Generate the arr_dmmv_* and binary-op aggregate tables that the upstream
# shader generator declares but never emits.
#
# Why this file exists
# --------------------
# vulkan-shaders-gen.cpp declares these tables in the header (lines 1178-1226 for
# add/sub/mul/div/add_rms, lines 1235-1275 for arr_dmmv_*) but only writes their
# definitions into the aggregate "src" stream when
# basename(input_filepath) == "mul_mat_vec.comp" / "<op>.comp". That same code
# path also walks the per-variant .spv files and `continue`s on the first missing
# one, so none of these definitions ever reach target_cpp. Without them,
# libllama-jni.so always fails to link with `undefined symbol arr_dmmv_*` /
# `undefined symbol add_data`.
#
# These are pure C++ aggregates: arr_dmmv_<type>_f32 packs the three
# implementations (default / subgroup / subgroup_no_shmem) of one matmul variant
# so the runtime can pick by device subgroup support. We reproduce the generator's
# exact template here, and only emit a table when all of its base symbols exist.
#
# NOTE: keep this file ASCII-only. PowerShell 5.1 reads BOM-less .ps1 files as
# ANSI/GBK, and a stray non-ASCII byte inside a comment can swallow the newline
# and turn the comment into parse errors.

$vkDir   = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$hpp     = Join-Path $vkDir 'ggml-vulkan-shaders.hpp'
$outFile = Join-Path $PSScriptRoot 'arr_dmmv_tables.comp.cpp'

$hdr = [System.IO.File]::ReadAllText($hpp)

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('#include "ggml-vulkan-shaders.hpp"')
$lines.Add('')
$lines.Add('// Generated by gen_arr_dmmv_tables.ps1 - see that script for why this exists.')

# ---------------------------------------------------------------------------
# arr_dmmv_* tables, template from vulkan-shaders-gen.cpp:1240-1255
# ---------------------------------------------------------------------------
$emitted = 0
foreach ($m in [regex]::Matches($hdr, 'extern const void \* (arr_dmmv_(?:id_)?[a-z0-9_]+)_data\[3\];')) {
    # The capture includes the trailing "_data", because that is what the
    # declaration spells. Strip it, otherwise the probe below looks for
    # "..._data_data[]" and silently matches nothing.
    $stem = $m.Groups[1].Value
    if ($stem.EndsWith('_data')) { $stem = $stem.Substring(0, $stem.Length - 5) }

    # Rebuild the base shader name the way the generator does, by concatenation,
    # so the two sides cannot drift:
    #   table = "arr_dmmv_"    + <rest>   e.g. arr_dmmv_f32_f16_f32
    #   base  = "mul_mat_vec_" + <rest>   e.g. mul_mat_vec_f32_f16_f32
    $tail = $stem.Substring('arr_dmmv_'.Length)
    $sym0 = 'mul_mat_vec_' + $tail

    $ok = $true
    foreach ($s in @($sym0,
                     "${sym0}_subgroup",
                     "${sym0}_subgroup_no_shmem")) {
        # NOTE: checked inline on purpose. Resolving the script-level $hdr from
        # inside a helper function proved unreliable here, and a helper returning
        # a wrong false silently produced an empty file.
        if (-not ($hdr.Contains("extern const unsigned char ${s}_data[];") -and
                  $hdr.Contains("extern const uint64_t ${s}_len;"))) { $ok = $false; break }
    }
    if (-not $ok) { continue }

    $lines.Add("const void * ${stem}_data[3] = {${sym0}_data, ${sym0}_subgroup_data, ${sym0}_subgroup_no_shmem_data};")
    $lines.Add("const uint64_t ${stem}_len[3] = {${sym0}_len, ${sym0}_subgroup_len, ${sym0}_subgroup_no_shmem_len};")
    $emitted++
}

# ---------------------------------------------------------------------------
# add / sub / mul / div / add_rms [2][2][2] tables,
# template from vulkan-shaders-gen.cpp:1178-1226. suffixes[] = {"_f32", "_f16"},
# index 0 = f32, index 1 = f16.
# ---------------------------------------------------------------------------
$suffixes = @('_f32', '_f16')
$opLines = New-Object System.Collections.Generic.List[string]
$opEmitted = 0

foreach ($op in @('add', 'sub', 'mul', 'div', 'add_rms')) {
    $ok = $true
    foreach ($ia in 0, 1) {
        foreach ($ib in 0, 1) {
            foreach ($ic in 0, 1) {
                $s = "$op$($suffixes[$ia])$($suffixes[$ib])$($suffixes[$ic])"
                if (-not ($hdr.Contains("extern const unsigned char ${s}_data[];") -and
                          $hdr.Contains("extern const uint64_t ${s}_len;"))) { $ok = $false }
            }
        }
    }
    if (-not $ok) { Write-Warning "skip $op : base shader variants incomplete"; continue }

    # Explicit brace construction for {2,2,2}:
    #   <T> = { <T>0, <T>1 }              where
    #   <T>i = { <T>i0, <T>i1 }, <T>ij = { <T>ij0, <T>ij1 }
    # => level 1 and level 2 each contribute '{' ... '}'. We append a trailing
    # comma to every group and then strip exactly one before adding ';'.
    $d = "const void * ${op}_data[2][2][2] = {"
    $l = "const uint64_t ${op}_len[2][2][2] = {"
    for ($a = 0; $a -lt 2; $a++) {
        $d += '{'
        $l += '{'
        for ($b = 0; $b -lt 2; $b++) {
            $d += '{'
            $l += '{'
            for ($c = 0; $c -lt 2; $c++) {
                $s = "$op$($suffixes[$a])$($suffixes[$b])$($suffixes[$c])"
                $d += "${s}_data,"
                $l += "${s}_len,"
            }
            $d += '},'
            $l += '},'
        }
        $d += '},'
        $l += '},'
    }
    # drop the trailing comma, then close the array
    $d = $d.Substring(0, $d.Length - 1) + '};'
    $l = $l.Substring(0, $l.Length - 1) + '};'
    $opLines.Add($d)
    $opLines.Add($l)
    $opEmitted++
}

if ($opEmitted -gt 0) {
    $lines.Add('')
    $lines.Add('// add/sub/mul/div/add_rms [2][2][2] aggregate tables.')
    foreach ($x in $opLines) { $lines.Add($x) }
}

# UTF-8 without BOM, so the generated C++ stays pure ASCII either way.
[System.IO.File]::WriteAllLines($outFile, $lines, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "wrote $outFile"
Write-Host "arr_dmmv tables: $emitted groups ($($emitted * 2) symbols)"
Write-Host "binary-op tables: $opEmitted groups ($($opEmitted * 2) symbols)"
